version: '3'
services:
  postgres:
    image: postgres:12
    container_name: postgres
    environment:
      POSTGRES_DB: hw03
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    
  mongo:
    image: mongo:5
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - ./storage/mongo/mongo_repl-1/data/db:/data/db